auth_enabled: false
schema_config:
  configs:
    - from: 2020-10-26
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
ruler:
  enable_api: true
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  alertmanager_url: http://alertmanager:9093/
ingestion_rate_limit: 4
ingestion_burst_size: 8
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 1209600s
storage:
  filesystem:
    chunks_directory: /loki/chunks
    rules_directory: /loki/rules
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
    chunks_directory: /loki/chunks
