global:
  resolve_timeout: 5m
route:
  receiver: 'web.hook'
  routes:
    - matchers:
        - name: severity
          value: critical
          regex: false
      receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:3000/api/alerts'
