version: "3.9"
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - --config.file=/etc/alertmanager/config.yml
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
    command:
      - --config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail:/etc/promtail
      - /var/log:/var/log
    command:
      - --config.file=/etc/promtail/config.yml
    networks:
      - monitoring
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
    volumes:
      - ./tempo:/etc/tempo
    command:
      - --config.file=/etc/tempo/tempo.yaml
    networks:
      - monitoring

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    depends_on:
      - prometheus
      - loki
      - alertmanager
      - tempo
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
